module Task1
{
	interface Toaster
	{
		attribute boolean	is_toasting;
		attribute short		toast_colour;

		boolean	insert_toast();
		boolean eject_toast(out string toast_desc);

		short	get_toast_colour();
	};
};
